package ascii

import (
	"crypto/sha256"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
)

// The golden files are transcribed from the supplied audit, not generated by
// Generator. The examples omit padding at line ends and empty outer rows.
func TestAuditExamples(t *testing.T) {
	for _, tc := range []struct {
		banner string
		text   string
	}{
		{"standard", "{123}\n<Hello> (World)!"},
		{"thinkertoy", "123 T/fs#R"},
	} {
		t.Run(tc.banner, func(t *testing.T) {
			want, err := os.ReadFile(filepath.Join("testdata", tc.banner+"_audit.golden"))
			if err != nil {
				t.Fatal(err)
			}
			got, err := NewGenerator("../..").Generate(tc.text, tc.banner)
			if err != nil {
				t.Fatal(err)
			}
			lines := strings.Split(got, "\n")
			for i := range lines {
				lines[i] = strings.TrimRight(lines[i], " ")
			}
			got = strings.Trim(strings.Join(lines, "\n"), "\n") + "\n"
			if got != string(want) {
				t.Errorf("audit example mismatch\ngot:\n%s\nwant:\n%s", got, want)
			}
		})
	}
}

func TestBundledBanners(t *testing.T) {
	// Pin the complete bundled fonts, including invisible space padding.
	checksums := map[string]string{
		"standard":   "e194f1033442617ab8a78e1ca63a2061f5cc07a3f05ac226ed32eb9dfd22a6bf",
		"shadow":     "26b94d0b134b77e9fd23e0360bfd81740f80fb7f6541d1d8c5d85e73ee550f73",
		"thinkertoy": "092d0cde973bfbb02522f18e00e8612e269f53bac358bb06f060a44abd0dbc52",
	}
	for banner, checksum := range checksums {
		t.Run(banner, func(t *testing.T) {
			data, err := os.ReadFile(filepath.Join("../..", banner+".txt"))
			if err != nil {
				t.Fatal(err)
			}
			if got := fmt.Sprintf("%x", sha256.Sum256(data)); got != checksum {
				t.Errorf("font changed: SHA-256 = %s, want %s", got, checksum)
			}
			generator := NewGenerator("../..")
			for char := rune(32); char <= 126; char++ {
				art, err := generator.Generate(string(char), banner)
				if err != nil {
					t.Fatalf("glyph %q: %v", char, err)
				}
				rows := strings.Split(strings.TrimSuffix(art, "\n"), "\n")
				if len(rows) != 8 {
					t.Fatalf("glyph %q: got %d rows, want 8", char, len(rows))
				}
				for _, row := range rows {
					if len(row) != len(rows[0]) || len(row) == 0 {
						t.Fatalf("glyph %q has inconsistent padding", char)
					}
				}
			}
		})
	}
}

func TestGenerateSupportsEveryBanner(t *testing.T) {
	generator := NewGenerator("../..")
	for _, banner := range []string{"standard", "shadow", "thinkertoy"} {
		t.Run(banner, func(t *testing.T) {
			art, err := generator.Generate("A", banner)
			if err != nil {
				t.Fatalf("Generate() вернул ошибку: %v", err)
			}
			if lines := strings.Count(art, "\n"); lines != 8 {
				t.Fatalf("получено %d строк, ожидалось 8", lines)
			}
			if strings.TrimSpace(art) == "" {
				t.Fatal("ASCII-арт не должен быть пустым")
			}
		})
	}
}

func TestGeneratePreservesNewlines(t *testing.T) {
	generator := NewGenerator("../..")
	tests := []struct {
		name  string
		text  string
		lines int
	}{
		{name: "одна строка", text: "A", lines: 8},
		{name: "две строки", text: "A\nB", lines: 16},
		{name: "пустая строка между словами", text: "A\n\nB", lines: 17},
		{name: "перевод строки в конце", text: "A\n", lines: 9},
		{name: "два перевода строки в конце", text: "A\n\n", lines: 10},
		{name: "буквальная последовательность", text: `A\nB`, lines: 16},
		{name: "CRLF", text: "A\r\nB", lines: 16},
		{name: "CR", text: "A\rB", lines: 16},
		{name: "перевод строки в начале", text: "\nA", lines: 9},
		{name: "один перевод строки", text: "\n", lines: 1},
		{name: "два перевода строки", text: "\n\n", lines: 2},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			art, err := generator.Generate(test.text, "standard")
			if err != nil {
				t.Fatalf("Generate() вернул ошибку: %v", err)
			}
			if lines := strings.Count(art, "\n"); lines != test.lines {
				t.Fatalf("получено %d строк, ожидалось %d", lines, test.lines)
			}
		})
	}
}

func TestGenerateValidation(t *testing.T) {
	generator := NewGenerator("../..")
	tests := []struct {
		name   string
		text   string
		banner string
		target error
	}{
		{name: "пустой текст", text: "", banner: "standard", target: ErrEmptyText},
		{name: "неизвестный баннер", text: "Hello", banner: "other", target: ErrInvalidBanner},
		{name: "не ASCII", text: "Привет", banner: "standard", target: ErrInvalidText},
		{name: "слишком длинный", text: strings.Repeat("a", 1001), banner: "standard", target: ErrTextTooLong},
		{name: "табуляция", text: "A\tB", banner: "standard", target: ErrInvalidText},
		{name: "нулевой байт", text: "\x00", banner: "standard", target: ErrInvalidText},
		{name: "DEL", text: "\x7f", banner: "standard", target: ErrInvalidText},
		{name: "ошибочный UTF-8", text: "\xff", banner: "standard", target: ErrInvalidText},
		{name: "путь вместо баннера", text: "Hello", banner: "../../etc/passwd", target: ErrInvalidBanner},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			_, err := generator.Generate(test.text, test.banner)
			if !errors.Is(err, test.target) {
				t.Fatalf("ошибка %v, ожидалась %v", err, test.target)
			}
		})
	}
}

func TestValidateTextBoundaries(t *testing.T) {
	if err := ValidateText("", true); err != nil {
		t.Fatalf("allowEmpty = true: %v", err)
	}
	if err := ValidateText(strings.Repeat("A", 1000), false); err != nil {
		t.Fatalf("1000 characters should be accepted: %v", err)
	}
	if _, err := NewGenerator("../..").Generate(strings.Repeat("A", 1000), "standard"); err != nil {
		t.Fatalf("maximum-length rendering: %v", err)
	}
}

func TestBannerLineEndings(t *testing.T) {
	data, err := os.ReadFile("../../standard.txt")
	if err != nil {
		t.Fatal(err)
	}
	want, err := NewGenerator("../..").Generate("ASCII !~", "standard")
	if err != nil {
		t.Fatal(err)
	}
	for name, content := range map[string]string{
		"CRLF":                  strings.ReplaceAll(string(data), "\n", "\r\n"),
		"without final newline": strings.TrimSuffix(string(data), "\n"),
	} {
		t.Run(name, func(t *testing.T) {
			dir := t.TempDir()
			writeBanner(t, dir, content)
			got, err := NewGenerator(dir).Generate("ASCII !~", "standard")
			if err != nil {
				t.Fatal(err)
			}
			if got != want {
				t.Fatal("line endings changed the rendered art")
			}
		})
	}
}

func TestMalformedBanners(t *testing.T) {
	data, err := os.ReadFile("../../standard.txt")
	if err != nil {
		t.Fatal(err)
	}
	lines := strings.Split(strings.TrimSuffix(string(data), "\n"), "\n")
	for _, tc := range []struct {
		name string
		edit func([]string) []string
	}{
		{"empty", func([]string) []string { return nil }},
		{"truncated", func(rows []string) []string { return rows[:len(rows)-1] }},
		{"extra line", func(rows []string) []string { return append(rows, "") }},
		{"missing separator", func(rows []string) []string { rows[9] = " "; return rows }},
		{"inconsistent width", func(rows []string) []string { rows[10] += " "; return rows }},
		{"control character", func(rows []string) []string { rows[10] = "\t" + rows[10][1:]; return rows }},
		{"non-ASCII glyph", func(rows []string) []string { rows[10] = "é" + rows[10][2:]; return rows }},
	} {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			content := strings.Join(tc.edit(append([]string(nil), lines...)), "\n") + "\n"
			writeBanner(t, dir, content)
			_, err := NewGenerator(dir).Generate("Hello", "standard")
			if !errors.Is(err, ErrMalformedBanner) {
				t.Fatalf("got %v, want ErrMalformedBanner", err)
			}
		})
	}
}

func TestBannerChangesAfterSuccessfulRequest(t *testing.T) {
	data, err := os.ReadFile("../../standard.txt")
	if err != nil {
		t.Fatal(err)
	}
	dir := t.TempDir()
	writeBanner(t, dir, string(data))
	generator := NewGenerator(dir)
	if _, err := generator.Generate("Hello", "standard"); err != nil {
		t.Fatal(err)
	}
	if err := os.Remove(filepath.Join(dir, "standard.txt")); err != nil {
		t.Fatal(err)
	}
	if _, err := generator.Generate("Hello", "standard"); !errors.Is(err, ErrBannerNotFound) {
		t.Fatalf("deleted banner: got %v, want ErrBannerNotFound", err)
	}
	writeBanner(t, dir, "broken\n")
	if _, err := generator.Generate("Hello", "standard"); !errors.Is(err, ErrMalformedBanner) {
		t.Fatalf("corrupted banner: got %v, want ErrMalformedBanner", err)
	}
	writeBanner(t, dir, string(data))
	if _, err := generator.Generate("Hello", "standard"); err != nil {
		t.Fatalf("repaired banner: %v", err)
	}
}

func TestConcurrentGeneration(t *testing.T) {
	generator := NewGenerator("../..")
	var wg sync.WaitGroup
	for _, banner := range []string{"standard", "shadow", "thinkertoy"} {
		want, err := generator.Generate("Concurrent!\n123", banner)
		if err != nil {
			t.Fatal(err)
		}
		for i := 0; i < 12; i++ {
			wg.Add(1)
			go func(banner, want string) {
				defer wg.Done()
				got, err := generator.Generate("Concurrent!\n123", banner)
				if err != nil || got != want {
					t.Errorf("concurrent %s generation: error %v, output equal %v", banner, err, got == want)
				}
			}(banner, want)
		}
	}
	wg.Wait()
}

func writeBanner(t *testing.T, dir, content string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, "standard.txt"), []byte(content), 0600); err != nil {
		t.Fatal(err)
	}
}

func TestMissingBannerFile(t *testing.T) {
	generator := NewGenerator(t.TempDir())
	_, err := generator.Generate("Hello", "standard")
	if !errors.Is(err, ErrBannerNotFound) {
		t.Fatalf("ошибка %v, ожидалась ErrBannerNotFound", err)
	}
}
